### ISSUE TITLE
 Exception: Failed to parse OTIO file: No adapter for suffix 'edl'

### ISSUE THREAD

**Issue by nekrasovdmitriy** [cgwire/zou#830]
**Context**

Studio name: Freelance
Kitsu version: 0.19.45
Production type: Short film

**Describe the bug**

There is an error on .edl file uploading to create shots:  
`An error occurred while uploading your EDL. Exception: Failed to parse OTIO file: No adapter for suffix 'edl' on file '/opt/zou/tmp/**********.edl'`

**Screenshots**

![Снимок экрана 2024-07-07 в 08 52 37](https://github.com/cgwire/kitsu/assets/18664106/eb74bfac-994e-4f99-97ac-ed08630d3283)

**Desktop (please complete the following information):**

 - OS: Macos 14.5
 - Browser: Safari 
 - Version 17.5

**Comment by EvanBldy** [comment]
Hi @nekrasovdmitriy,
It was because we have upgraded OTIO, but they have separated the extensions in another package (see here: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/releases/tag/v0.17.0).
It will be fixed for the next release (next Tuesday).
I close this issue, can you reopen it if you still have any related problems?
